package main;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import main.cadastroCompetidor;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danilo-PC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("racing-flag.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barraMenu = new javax.swing.JMenuBar();
        corridaMenu = new javax.swing.JMenu();
        inserirCorrida = new JMenuItem(new AbstractAction("My Menu Item") {
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, "My Goodness, this is so concise");
            }
        });
        competidorMenu = new javax.swing.JMenu();
        inserirCompetidor =  new JMenuItem(new AbstractAction("My Menu Item") {
            public void actionPerformed(ActionEvent e) {
                cadastroCompetidor cadastroCompetidor = new cadastroCompetidor();
                cadastroCompetidor.setVisible(true);
                painelPrincipal.add(cadastroCompetidor);
            }
        });
        jMenuItem1 = new javax.swing.JMenuItem();
        capturaMenu = new javax.swing.JMenu();
        iniciarCaptura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cachorro do Mato");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cronômetro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Competidor", "Tempo Abs", "Tempo Volta", "Volta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        painelPrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelPrincipal.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        corridaMenu.setText("Corrida");

        inserirCorrida.setText("Nova");
        inserirCorrida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserirCorridaMouseClicked(evt);
            }
        });
        inserirCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirCorridaActionPerformed(evt);
            }
        });
        corridaMenu.add(inserirCorrida);

        barraMenu.add(corridaMenu);

        competidorMenu.setText("Competidor");
        competidorMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                competidorMenuMouseClicked(evt);
            }
        });

        inserirCompetidor.setText("Adicionar");
        inserirCompetidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserirCompetidorMouseClicked(evt);
            }
        });
        inserirCompetidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirCompetidorActionPerformed(evt);
            }
        });
        competidorMenu.add(inserirCompetidor);

        jMenuItem1.setText("Excluir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        competidorMenu.add(jMenuItem1);

        barraMenu.add(competidorMenu);

        capturaMenu.setText("Captura");
        capturaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capturaMenuMouseClicked(evt);
            }
        });

        iniciarCaptura.setText("Iniciar captura");
        iniciarCaptura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarCapturaMouseClicked(evt);
            }
        });
        iniciarCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarCapturaActionPerformed(evt);
            }
        });
        capturaMenu.add(iniciarCaptura);

        barraMenu.add(capturaMenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        getAccessibleContext().setAccessibleName("frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarCapturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarCapturaActionPerformed

    private void inserirCompetidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserirCompetidorMouseClicked
cadastroCompetidor cadastroCompetidor = new cadastroCompetidor();
        cadastroCompetidor.setVisible(true);
        painelPrincipal.add(cadastroCompetidor);
    }//GEN-LAST:event_inserirCompetidorMouseClicked

    private void inserirCompetidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirCompetidorActionPerformed
       
    }//GEN-LAST:event_inserirCompetidorActionPerformed

    private void iniciarCapturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarCapturaMouseClicked
 JOptionPane.showMessageDialog(null, "My Goodness, this is so concise");        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarCapturaMouseClicked

    private void inserirCorridaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserirCorridaMouseClicked
   JOptionPane.showMessageDialog(null, "My Goodness, this is so concise");     // TODO add your handling code here:
    }//GEN-LAST:event_inserirCorridaMouseClicked

    private void inserirCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirCorridaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirCorridaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void competidorMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_competidorMenuMouseClicked
        
    // TODO add your handling code here:
    }//GEN-LAST:event_competidorMenuMouseClicked

    private void capturaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capturaMenuMouseClicked
        seletorCompetidor seletorCompetidor = new seletorCompetidor();
        seletorCompetidor.setVisible(true);
        painelPrincipal.add(seletorCompetidor);
        
        

        
    }//GEN-LAST:event_capturaMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu capturaMenu;
    private javax.swing.JMenu competidorMenu;
    private javax.swing.JMenu corridaMenu;
    private javax.swing.JMenuItem iniciarCaptura;
    private javax.swing.JMenuItem inserirCompetidor;
    private javax.swing.JMenuItem inserirCorrida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
